import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import styles3 from '@/styles/layout.module.css'
import Holder from './holder';
import ColorList from '../components/color-list'
import { initializeApp } from "firebase/app";
import { getStorage, ref, uploadBytesResumable, getDownloadURL } from 'firebase/storage'
import "firebase/firestore"
import { doc, setDoc , getFirestore } from "firebase/firestore"; 
import { useState } from 'react';
import { log } from 'console';
const inter = Inter({ subsets: ['latin'] })

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};

// Intialize the firebase
const app = initializeApp(firebaseConfig);
// Get the storgae location in firbase
const storage = getStorage();
const db = getFirestore();
  
let tempUrl ="";
var names="User";




export default function Home({ colorsFromAPIConverted, colorsFromAPIOriginal }:{colorsFromAPIConverted:string[], colorsFromAPIOriginal:string[]}) {
// Get storage location and add to new file location before sending to firebase.
// ref ask the storage and location for the file to put it in a readable format that helps with upload.
// Example of get file location
// ref(storage,"image/photo");

 let storeCopy=  ref(storage,"images/"+names+"/Copy");
let store=  ref(storage,"images/"+names+"/Original");

let storeFile= ref(storage,"files/"+names);

// Store image file inside
var imageFile: any;

var indexFile: any;

// Starting image
var starturl="gs://colorswapper-f6b50.appspot.com/images/";


// useState are sets of values and array that can change onloading and change elements

// Hides error codes 
const [errorhide,setErrorhide]= useState(true);

//Hide elements after user upload correctly
const [hide,setHidden]= useState(false);
//Set error messages
const [error,setError]= useState("");

//Get changes for image src 
const [imageUrl,setImage]=useState(starturl);

const [imageUrl2,setImage2]=useState(starturl);
// Start value for user name

// Check for any changes in src
function Getname(e: any){

 names=e;
}

// Get image file from file input
async function Getfile(images: any) {
  // input store files into a array and is at first place of the array
  imageFile = images[0];
   
  // Get type from image file
   const meta = {
    contentType: imageFile.type
  }

// Send to firebase by entering location of the file and name ,what inside the file and the file type.
  let upload=await uploadBytesResumable(store, imageFile, meta);
}

 async function getMulti(index:any){
  indexFile=index[0];
  
  const meta2={
    contextType: indexFile.type
  }
 //This line always throws a typing error, ignore
let uploadFile=await uploadBytesResumable(storeFile, indexFile, meta2);
}

// Send file to the firebase on button click
async function Upload() {

  // Store url of firebase location using store ref
  await getDownloadURL(store).then(function(url){
    tempUrl = url;
    setImage(url);
    setDoc(doc(db,'users',names),{
    orginal: url,
    check: false,
    username: names
    });
  });
  await getDownloadURL(storeCopy).then(function(url2){
      setImage2(url2);
 
    });
  }



  //Change elements and call up load on click
  const Clicking= async () => {
   
    const response = await fetch('http://localhost:8080/main/convert', {
    
    mode:'no-cors'
  

    });

    if(imageFile!=null && names!="" && indexFile!=null)
    { 
      Upload();
      setErrorhide(true);
      setHidden(true);
      //Example of image being used
    //   setImage("/check.png");
    }
    else
    {
      setErrorhide(false);
      setHidden(false);
      setError("Error: User has not selected a file or not input user name")
    }  
  }
  return (
    <>
      <Head>
        <title id="lol">481 Color Swapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <h1 className={styles3.header}> Color Swapper </h1>
      </Head>
      <main className={styles.main}>
        <div>
          <h1 hidden={!hide} className={styles3.other}>Images is now uploaded</h1>
          <p color='red' hidden={errorhide}>{error} </p>
          <p hidden={hide} className={styles3.other}>Input User name and file to Convert</p>
          <p hidden={!hide}>Backlog Item 1 Space</p>
          <input type='file' hidden={hide} accept='image./png' onChange={(images)=>Getfile(images.target.files)}></input>
          <input type='file' hidden={hide} accept='dat' onChange={(index)=>getMulti(index.target.files)}></input>
          <button  id="btn" hidden={hide} onClick={Clicking}  >Upload</button>
        </div>
        <p>
          <img src={imageUrl} height={500} width={500} hidden={!hide}/>
          <img src={imageUrl2} height={500} width={500} hidden={!hide}/>
        </p>

        <div>
          <div style={{float: 'left'}}>
            <h2>Original Image Colors</h2>
            <ColorList colorList={colorsFromAPIOriginal}></ColorList>
          </div>
          <div style={{float: 'left'}}>
            <h2>Converted Image Colors</h2>
            <ColorList colorList={colorsFromAPIConverted}></ColorList>
          </div>
        </div>
        <div>
          <Holder/>
        </div>
      </main>
      <footer className={styles3.footer}>
            <p> This website is the creation of Free Labor. All rights reserverd and copyright 2023.</p>
        </footer>
    </>
  )
}

 export async function getServerSideProps(context:any) {
  const res = await fetch('http://localhost:8080/colorConversion/convertedImageColors');
  const colorsFromAPIConverted = await res.json();
  const res2 = await fetch('http://localhost:8080/colorConversion/originalImageColors');
  const colorsFromAPIOriginal = await res2.json();

  return {
    props: { colorsFromAPIConverted, colorsFromAPIOriginal }, // will be passed to the page component as props
  }
}
