import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function displayImage()
{
  let returnValue: any;
  returnValue = document.getElementById("testPic")!.onchange = function(event) {getFile(event)};
  var test = document.getElementById("textPic");
  document.getElementById("picDisplayer")!.innerHTML = "<img src=\" " + document.getElementById("testPic") + "\">";
  return returnValue;
}

function getFile(e:Event | null) {
  if(e != null){
    // @ts-ignore: Object is possibly 'null'.
    let imageFile = (e.target as HTMLInputElement).files[0];
    console.log(imageFile.name);
  }
}

export default function Home() { 
  return (
    <main>
      <head>
        <title>481 Color Swapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className={styles.main}>
        <div>
          <input type="file" id="testPic" name="textPic" accept="image/*"></input>
          <button onClick={displayImage}> Submit </button>
          <p id="picDisplayer">  </p>
        </div>
        <div>
          <p>Backlog Item 3 Space</p>
        </div>
        <div>

          
        </div>
      </main>
    
  )
  )
}
