import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { initializeApp } from "firebase/app";
import {getStorage, ref ,uploadBytesResumable,getDownloadURL} from 'firebase/storage'
import "firebase/firestore"
import { env } from 'process';
const inter = Inter({ subsets: ['latin'] })




// Store image file inside
var imageFile: any;

// Get the Config to the firebase for connection

const firebaseConfig = {

  apiKey:"AIzaSyDt9XmPpyC578583K5H2n4e50p6Lj3qa08",

  authDomain: "colorswapper-f6b50.firebaseapp.com",

  projectId: "colorswapper-f6b50",

  storageBucket: "colorswapper-f6b50.appspot.com",

  messagingSenderId: "617843414878",

  appId: "1:617843414878:web:80925e8c80b5f3ff84e1cf",

  measurementId: "G-0B05VSYTPH"

};

// Intialize the firebase
const app = initializeApp(firebaseConfig);

// Get the storgae location in firbase
const storage =getStorage();



// Check for any changes in src
var checking="";



// Get image file from file input
function Getfile(images:any)
{
  // input store files into a array and is at first place of the array
  imageFile=images[0];

}



// Send file ro the firebase on button click
function Clicking()
{


// Get type from image file
  const meta={
  
		contentType: imageFile.type
		}



  // Get storage location and add to new file location before sending to firebase.
  // ref ask the storage and location for the file to put it in a readable format for the upload.
	let store= ref(storage,"images/Oringal");
  let storeCopy=ref(storage,"images/Copy");

  // Send to firebase by entering location of the file and name ,what inside the file and the file type.
	let upload=uploadBytesResumable(store,imageFile,meta);
  let Copyupload=uploadBytesResumable(storeCopy,imageFile,meta);


  // Example of get file location
	// ref(storage,"image/photo");

// Get store locactaion to url
  getDownloadURL(store).then(function(url){
  
    checking=url; 
    
    }

    );}
 

export default function Home() {
  return (
    <>
      <Head>
        <title>481 Color Swapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p>Backlog Item 1 Space</p>
          <Image src={checking}
          width={500}
          height={500}
          alt=""/>
          <input type='file'  accept='image./png' onChange={(images)=>Getfile(images.target.files)}></input>
          <button  id="btn"  onClick={Clicking}>Upload</button>
        </div>
        <div>
          <p>Backlog Item 3 Space</p>
        </div>
      </main>
    </>
  )
}
