import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { getStorage } from "firebase/storage";
const inter = Inter({ subsets: ['latin'] })

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyDt9XmPpyC578583K5H2n4e50p6Lj3qa08",
  authDomain: "colorswapper-f6b50.firebaseapp.com",
  projectId: "colorswapper-f6b50",
  storageBucket: "colorswapper-f6b50.appspot.com",
  messagingSenderId: "617843414878",
  appId: "1:617843414878:web:80925e8c80b5f3ff84e1cf",
  measurementId: "G-0B05VSYTPH"
};
const storage = getStorage(app);

// Initialize Firebase
const app = initializeApp(firebaseConfig);

export default function Home() {
  return (
    <>
      <Head>
        <title>481 Color Swapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p>Backlog Item 1 Space</p>
        </div>
        <div>
          <p>Backlog Item 3 Space</p>
        </div>
      </main>
    </>
  )
}
