import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import { initializeApp } from "firebase/app";
import { getStorage, ref, uploadBytesResumable, getDownloadURL, getBytes } from 'firebase/storage'
import "firebase/firestore"
import { doc, setDoc, getFirestore, documentId } from "firebase/firestore";
import { env } from 'process';
const inter = Inter({ subsets: ['latin'] })

// Store image file inside
var imageFile: any;

// Get the Config to the firebase for connection

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};

// Intialize the firebase
const app = initializeApp(firebaseConfig);

// Get the storgae location in firbase
const storage = getStorage();
const db = getFirestore();


// Check for any changes in src
var names: any;
function Getname(e: any) {
  names = e;
}

// Get image file from file input
function Getfile(images: any) {
  // input store files into a array and is at first place of the array
  imageFile = images[0];
}



// Send file ro the firebase on button click
function Clicking() {
  // Get type from image file
  const meta = {
    contentType: imageFile.type
  }


  // Get storage location and add to new file location before sending to firebase.
  // ref ask the storage and location for the file to put it in a readable format for the upload.
  let store = ref(storage, "images/" + names + "/Oringal");
  let storeCopy = ref(storage, "images/" + names + "/Copy");;


  // Send to firebase by entering location of the file and name ,what inside the file and the file type.
  let upload = uploadBytesResumable(store, imageFile, meta);
  let Copyupload = uploadBytesResumable(storeCopy, imageFile, meta);


  // Example of get file location
  // ref(storage,"image/photo");

  //Wait until its the url is ready.
  for (var i = 1000; i <= 0; i--) {

    // Get store locactaion to url
    getDownloadURL(store).then(function (url) {
      getDownloadURL(storeCopy).then(function (url2) {
        //
      });
    }
    );
  }
}




export default function Home() {
  return (
    <>
      <Head>
        <title id="lol">481 Color Swapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="free-labor-481-color-swapper-front-end/src/scripts/listCollasper.js"></script>
      </Head>
      <main className={styles.main}>
        <div>
          <p>Backlog Item 1 Space</p>
          <input type='text' onChange={(text) => Getname(text.target.value)}></input>
          <input type='file' accept='image./png' onChange={(images) => Getfile(images.target.files)}></input>
          <button id="btn" onClick={Clicking}>Upload</button>
        </div>
        <div>
          <p>Backlog Item 3 Space</p>
        </div>
        <div>
           <button type="button" className={styles.collapsible} id="collapsible"> Colors </button>
           <div className={styles.content}>
            <p> PlaceHolder </p>
           </div>
        </div>
      </main>
    </>
  )
}
